### PR TITLE
Add "how did you hear about us" field

### PR DESCRIPTION
**Pull request by stefancherubin**
Gotta find out how folks heard about us

### CODE REVIEW

**Comment by NicholasLYang** [comment]
Oh yeah, we should also add analytics

**Comment by NicholasLYang** [comment]
I'm not sure if we should add this as a mandatory field, as people who have already submitted will be kinda confused that they have to add more info

**Comment by stefancherubin** [comment]
As in, make a new component for analytics? Also, I guess we can make it optional, hopefully folks will consider doing that question.

**Comment by themichaelyang** [comment]
This looks good to me. Let's ask marketing if there are any other channels we should ask about.

**Pull request merged**
